Tools & Plugin: Dynamic Visual Studio path detection
Pagghiu/SaneCppLibraries pull request #18
Opened 2024-05-16 08:58 UTC by silent-tech

Instead of constant strings, "tools" and "plugin" modules detect VS path automatically.

2024-05-18 08:26 UTC, Pagghiu requested changes
The code in this PR is great to be merged as is!

I would just kindly request some cosmetic changes to the commits structure / naming:

1. Edit the name of the 7-zip commit
From:
Tools: 7-zip package version updated.

To

Tools: Update 7-zip to version 24.05

(notice no dot at the end, I think I need to fix the [Commit message format](https://github.com/Pagghiu/SaneCppLibraries/blob/main/CONTRIBUTING.md#commit-message-format) that talks about adding a dot when there is a further paragraph)

2. Squash the remaining commits to a single one
Suggested commit name:

Plugin: Detect Visual Studio path dynamically

or

Plugin: Add VisualStudioPathFinder to de-hardcode visual studio paths

Or in general just try to avoid using past tense (Add, Detect, Update instead of Added, Detected, Updated).

If you use a visual tool like [https://fork.dev](https://fork.dev) this is super easy to do with the interactive rebase.

https://github.com/Pagghiu/SaneCppLibraries/assets/5406873/917852b7-4ae9-4e7a-b836-45c04fb30465


Of course this can be done also with the git command line with the proper sequence of commands if you happen to know them (I don't! :sweat_smile:)

2024-05-18 08:26 UTC, Pagghiu commented on Tools/SC-package.cpp
Oh I see what's going on here, the link to `7zr.exe` is not versioned so every time they will update it, it will break this code 😞 
Thanks for noticing, this is really great.
I am wondering if there is some fixed URL at 7-zip.org where we could get a specific version.

2024-05-21 07:24 UTC, silent-tech commented
Thank you for your patience and detailed explanation. I am not a practiced contributor, but I am trying to learn it fast.

2024-05-21 17:47 UTC, merged

2024-05-21 17:49 UTC, Pagghiu commented
> Thank you for your patience and detailed explanation. I am not a practiced contributor, but I am trying to learn it fast.

You're actually the first contributor to this project 🎉 🥇!
Keep going 😄